### ISSUE TITLE
WikiExtractor git cloning error

### ISSUE THREAD

**Issue by SatanuG** [google-research/xtreme#102]
Hi,

When I am trying to run "download_data.sh" I am getting this error: 

```
+ echo '>Download external wikiextractor tool...'
>Download external wikiextractor tool...
+ OLDPWD=/home/satanu/xtreme/download/mewslix/tmp/dense_representations_for_entity_retrieval/mel
+ git clone git@github.com/attardi/wikiextractor.git tools/wikiextractor_repo
fatal: repository 'git@github.com/attardi/wikiextractor.git' does not exist
```
Is there a quick fix to this issue? I am also not able to clone the repo manually.

**Comment by sebastianruder** [comment]
The repo still exists, so you should be able to just clone it manually: https://github.com/attardi/wikiextractor
cc @bothameister

**Comment by SatanuG** [comment]
sorry my bad
