### ISSUE TITLE
kytea dependency

### ISSUE THREAD

**Issue by stefan-it** [google-research/xtreme#14]
Hi,

I've just seen that `kytea` is needed as depedency and will be cloned/installed in the installation script. 

But I couldn't find any usage in the python scripts (or any commandline usage), so is `kytea` really needed for the XTREME benchmark 🤔

**Comment by maksym-del** [comment]
Hi,

it is used by XLM tokenizer that is a part of the ```transformers``` library and needed for XLM models used in this work.

**Comment by stefan-it** [comment]
Thanks :)
