### ISSUE TITLE
Issue with panx preprocessing

### ISSUE THREAD

**Issue by stefan-it** [google-research/xtreme#16]
Hi,

I just wanted to re-produce the NER pipeline with the `bert-base-multilingual-cased` model using the installation instructions as provided in the readme.

Model training is working, but the prediction step did not work for some languages, because an exception is thrown here:

https://github.com/google-research/xtreme/blob/d25b4618bfe1c2a06ca07d7de18ea548f03d020f/third_party/utils_tag.py#L218

I did a bit of debugging and found the following:

For some languages, there are two consecutive empty lines in the test files and then the `utils_tag.py` script provides non-working `features`.

E.g. The test set for Vietnamese:

```bash
$ wc -l download/panx/test-vi.tsv
74967
```

With `cat -s` (squeeze option) consecutive empty lines are replaced by only one empty line:

```bash
$ cat -s download/panx/test-vi.tsv | wc -l
74966
```

With that command, consecutive empty lines can be detected. Then I wrote a script, that replaces these consecutive empty lines by only one:

```bash
for file in *.tsv
do
  sed -i 'N;/^\n$/D;P;D;' $file
done
```

and placed it into the `download/panx` folder.

After running this script, all test sets could be processed in the prediction step.

The problem with these consecutive empty lines only occur for NER (PoS pipeline is fine)! I'm not sure if this workaround has negative impact on the submission evaluation script 🤔

**Comment by sebastianruder** [comment]
Thanks for the note, Stefan! We'll take a look at the best way to fix this. cc @JunjieHu

**Comment by JunjieHu** [comment]
Hi Stefan, I've made a new pull request to fix this issue. Please use the new utils_preprocess.py file to preprocess the data once @sebastianruder merges the PR.

**Comment by melvinjosej** [comment]
Hi Stefan, I've merged Junjie's PR. Can you please verify that the latest code fixes this issue? I'm closing this issue. Please verify and reopen if it still persists.

**Comment by stefan-it** [comment]
@melvinjosej and @JunjieHu Thanks for the fix :)

I've just tested it, but the modifications in the `download_data.sh` (see https://github.com/google-research/xtreme/commit/37abe88cba1640ca30182d85a93fc728c280fc8f#diff-91e0bbb7c7da353deb7078bb3e3ed818) will lead to errors, because `cd`ing to the `panx_dataset` won't work - but the previous commit (see #15) was working :)

**Comment by melvinjosej** [comment]
@stefan-it  Ahh, you're right. Does this PR bring it back to a working state? 
https://github.com/google-research/xtreme/pull/20

I'll merge it in once you confirm.

**Comment by stefan-it** [comment]
PR is working :)

I can also confirm that there are no consect. empty lines in the datasets, I just re-ran the prediction for all languages :+1:

**Comment by melvinjosej** [comment]
Great. I've merged my PR. Thanks again @stefan-it for verifying :)
