### ISSUE TITLE
Tatoeba translation sentence pair alignment

### ISSUE THREAD

**Issue by choran** [google-research/xtreme#17]
Firstly thanks for the great dataset 👍 

I was looking through it and was just a little confused about the Tatoeba dataset layout

After running the `download_data.sh` script the Tatoeba dataset seems to be misaligned. I am not sure if this is an issue for the evaluation scripts but this is different from how they appear at source.

I manually ran the steps in `utils_preprocess.py` for Tatoeaba and downloaded the master data from [LASER](https://github.com/facebookresearch/LASER/tree/master/data/tatoeba/v1) and when comparing these files they are correctly aligned between sentence pairs

However, after running `utils_preprocess.py` the files appear to be out of alignment.

For example the the Spanish comparing files `es-en.es` and `es-en.en` they are aligned like this:
<img width="594" alt="Screenshot 2020-04-26 at 14 29 57" src="https://user-images.githubusercontent.com/15954251/80309098-97507f00-87ca-11ea-9b5f-9e5bfc4dcfa1.png">

When comparing the files from LASER directly, namely `tatoeba.spa-eng` and  `tatoeba.spa-eng.spa`
<img width="560" alt="Screenshot 2020-04-26 at 14 36 20" src="https://user-images.githubusercontent.com/15954251/80309188-5311ae80-87cb-11ea-8b6c-1bb98892dfbd.png">

Like I said, I am not sure if this is intentional for testing or not? And I cant see any other way to align them at the moment. So maybe this is just for testing? Either way, it might be a good idea to add some clarification as to whether this is supposed to be aligned or not

thanks again

Cathal

**Comment by JunjieHu** [comment]
Hi Cathal, 

You're correct. This mis-alignment is intentional in order to avoid a trivial submission for the test set. We'll add some clarification in the README.

Thanks,
Junjie

**Comment by choran** [comment]
Cool, I was just initially confused since some of the other datasets have training/dev/test splits so when this had only one set I wasnt sure was it just a test set or a dev set or did I miss something when I downloaded it
Thanks for the quick update 👍

**Comment by melvinjosej** [comment]
Cathal, closing this issue. Thanks for raising it.
