### ISSUE TITLE
Faiss requirement missing in install.sh and readme.md

### ISSUE THREAD

**Issue by anlausch** [google-research/xtreme#22]
For tatoeba, it seems like user have to install faiss (utils_retrieve.py)

**Comment by sebastianruder** [comment]
cc @JunjieHu

**Comment by JunjieHu** [comment]
@anlausch the anaconda environment should include the faiss during the installation. Please check this [line](https://github.com/JunjieHu/xtreme/blob/master/conda-env.txt#L106). Could you install the environment by `conda create --name xtreme --file conda-env.txt` and see if faiss is successfully installed?

**Comment by anlausch** [comment]
You are right!
