### ISSUE TITLE
Don't remove_qa_test_annotations

### ISSUE THREAD

**Issue by Liangtaiwan** [google-research/xtreme#27]
In utils_qa_test_annotations, all the qa testing data annotations are removed.
However, the annotations are needed when running scripts/eval_qa.sh.

I think that there is a better way to prevent cheating since it's not hard to get the original testing data.

**Comment by sebastianruder** [comment]
It's hard to prevent cheating in general given that the test sets of the datasets in XTREME are publicly available. By removing test labels, we mainly intend to prevent accidental cheating and inadvertent hill-climbing on the test data. Many of the datasets have dev sets available that can be used for validation.

**Comment by hit-computer** [comment]
@Liangtaiwan Hi, how do you get `mlqa_evaluation_v1.py` and `evaluate-v1.1.py` python files which are used in `scripts/eval_qa.sh`? Thank you very much!

**Comment by sebastianruder** [comment]
We have changed their location in a recent update. Instead of downloading them with the data, you can now find them directly in the `third_party` folder [here](https://github.com/google-research/xtreme/tree/master/third_party). Just update the corresponding paths.
