### ISSUE TITLE
MLQA results reproducability for XLM-R

### ISSUE THREAD

**Issue by hit-computer** [google-research/xtreme#38]
Hi, thanks for the benchmark and the accompanied code!

I am trying to replicate MLQA scores from the (XTREME) paper using this repo's code. I use `evaluate_mlqa.py` file to evaluate the result of XML-R model, but the score on `zh` language is wrong while the other is right. Here are my results

``` text
en  {"exact_match": 70.62985332182916, "f1": 83.3786980958141}                                                                                                                       
es  {"exact_match": 56.10127546164097, "f1": 73.58575605485278}                                                                                                                      
de  {"exact_match": 54.85941996900598, "f1": 69.47592323594147}                                                                                                                      
ar  {"exact_match": 45.7357075913777, "f1": 65.1863063068997}                                                                                                                        
hi  {"exact_match": 51.830012200081335, "f1": 68.98355428605254}                                                                                                                     
vi  {"exact_match": 51.30118289353958, "f1": 72.50031191585738}                                                                                                                      
zh  {"exact_match": 5.723184738174032, "f1": 19.154113403670923}
```

**Comment by sebastianruder** [comment]
Thanks for the question! There is an in the `squad_metrics.py` script of HuggingFace Transformers that does not work well for Chinese. Specifically, as Chinese doesn't use spaces, we don't need to execute the `get_final_text` function in [this line](https://github.com/huggingface/transformers/blob/master/src/transformers/data/metrics/squad_metrics.py#L501). If you set `final_text = tok_text` instead only for Chinese, then you should get the same scores.

**Comment by hit-computer** [comment]
@sebastianruder Thank you very much!

**Comment by lixin4ever** [comment]
@hit-computer hello, can you share which lines in `evaluate_mlqa.py` did you change to obtain the normal Chinese results?

**Comment by ruixiangcui** [comment]
@sebastianruder @hit-computer After I set `final_text = tok_text` in `squad_metrics.py`, and ran `predict_qa.py` and `eval_qa.py` again, I still got the same results for Chinese on MLQA.  Is there anything else I am missing? If I look at the predictions, most of them are very long, almost directly copying-pasting the context.
`{"exact_match": 4.944520147946272, "f1": 18.297195642566766}`

**Comment by lixin4ever** [comment]
> @sebastianruder @hit-computer After I set `final_text = tok_text` in `squad_metrics.py`, and ran `predict_qa.py` and `eval_qa.py` again, I still got the same results for Chinese on MLQA. Is there anything else I am missing? If I look at the predictions, most of them are very long, almost directly copying-pasting the context.
> `{"exact_match": 4.944520147946272, "f1": 18.297195642566766}`

+1

**Comment by ruixiangcui** [comment]
@lixin4ever It works for me now. To evaluate ZH, we have to first delete [this line](https://github.com/huggingface/transformers/blob/c8be8a9adb218ecc593c687020e952554a5a55b5/src/transformers/data/metrics/squad_metrics.py#L514), and then add  `final_text = tok_text` at line 514. After modifying `squad_metrics.py`, run `predict_qa.py` to get the updated predicted file, and then we can evaluate it again.

**Comment by lixin4ever** [comment]
@ruixiangcui It also works for me. Thanks.
