### ISSUE TITLE
Tatoeba code is broken

### ISSUE THREAD

**Issue by ritterng** [google-research/xtreme#49]
The file scripts/run_tatoeba.sh using the following command to call the tatoeba related python code:

``` shell
  python $REPO/third_party/run_retrieval.py \
  ...
```
However, the file run_retrieval.py has been renamed to evaluate_retrieval.py  in commit c168376

**Comment by sebastianruder** [comment]
Thanks for fixing this in PR https://github.com/google-research/xtreme/pull/48, which has now been merged.
