### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by blazejdolicki** [google-research/xtreme#6]
In README there's this sentence: "For every task, we provide a single script scripts/train.sh that fine-tunes pre-trained models implemented in the [Transformers] repo." It looks like you wanted to provide a link to https://github.com/huggingface/transformers but forgot to do it. Is that the case?

**Comment by sebastianruder** [comment]
Hey! Thanks for the note. Yes, that seems to be the case. 😅We'll fix that in the next PR.

**Comment by melvinjosej** [comment]
Thanks for pointing this out. This has been fixed now.
