### ISSUE TITLE
XTREME Leaderboard link in README doesn't work

### ISSUE THREAD

**Issue by ai-nikolai** [google-research/xtreme#7]
Hi thanks,

For this pretty cool work and evaluation benchmark.

There is an issue with your leaderboard link provided in the README  (https://research.google/xtreme/) 

Thanks.

**Comment by sebastianruder** [comment]
Hi Nikolai,
Thanks for the note! The website should go live in the next couple of days (we experienced some delays with getting it launched unfortunately). I'll post an update here once it is live.

**Comment by sebastianruder** [comment]
The XTREME website is now available [here](https://sites.research.google/xtreme). We'll add the dynamic leaderboard and submission portal shortly.
