### ISSUE TITLE
[bugs] All results 0 in test with the NER(PANX) task 

### ISSUE THREAD

**Issue by A11en0** [google-research/xtreme#99]
When I used `xlm-roberta-base` to run the NER task with the PANX dataset. In this testing stage, all test scores are returned as 0 for each language while the dev stage is fine.

```
02/17/2023 12:52:02 - INFO - __main__ -   ***** Evaluation result  in ro *****
02/17/2023 12:52:02 - INFO - __main__ -     f1 = 0.0
02/17/2023 12:52:02 - INFO - __main__ -     loss = 5.506586385611147
02/17/2023 12:52:02 - INFO - __main__ -     precision = 0.0
02/17/2023 12:52:02 - INFO - __main__ -     recall = 0.0
```

The same issue of #93.

**Comment by sebastianruder** [comment]
See https://github.com/google-research/xtreme/issues/93 for the resolution of this issue.
